package com.dotwait.md5;

import org.junit.Test;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Md5Test {
    @Test
    public void md5Test() throws NoSuchAlgorithmException {
        String buffer = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<env:Envelope\n" +
                "    xmlns:env=\"http://www.w3.org/2003/05/soap-envelope\">\n" +
                "    <env:Header>\n" +
                "        <auth:Authentication\n" +
                "            xmlns:auth=\"http://www.h3c.com/netconf/base:1.0\" env:mustUnderstand=\"true\">\n" +
                "            <auth:AuthInfo>100002970e66cf2b756f689e4cef8e6da600</auth:AuthInfo>\n" +
                "        </auth:Authentication>\n" +
                "    </env:Header>\n" +
                "    <env:Body>\n" +
                "        <rpc-reply\n" +
                "            xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\"\n" +
                "            xmlns:web=\"urn:ietf:params:xml:ns:netconf:base:1.0\" message-id=\"101\">\n" +
                "            <data>\n" +
                "                <top\n" +
                "                    xmlns=\"http://www.h3c.com/netconf/data:1.0\">\n" +
                "                    <WLANClient>\n" +
                "                        <ServiceTemplates>\n" +
                "                            <Template>\n" +
                "                                <Name>abc</Name>\n" +
                "                                <Enable>false</Enable>\n" +
                "                                <DefaultVlan>1</DefaultVlan>\n" +
                "                                <HideSsid>false</HideSsid>\n" +
                "                                <MaxClientCnt>0</MaxClientCnt>\n" +
                "                                <UserIsolation>false</UserIsolation>\n" +
                "                            </Template>\n" +
                "                            <Template>\n" +
                "                                <Name>lzxm</Name>\n" +
                "                                <Enable>true</Enable>\n" +
                "                                <SSID>lzxm</SSID>\n" +
                "                                <DefaultVlan>1</DefaultVlan>\n" +
                "                                <HideSsid>false</HideSsid>\n" +
                "                                <MaxClientCnt>0</MaxClientCnt>\n" +
                "                                <UserIsolation>false</UserIsolation>\n" +
                "                                <Description>3</Description>\n" +
                "                            </Template>\n" +
                "                            <Template>\n" +
                "                                <Name>kytest</Name>\n" +
                "                                <Enable>true</Enable>\n" +
                "                                <SSID>xkyTest</SSID>\n" +
                "                                <DefaultVlan>20</DefaultVlan>\n" +
                "                                <HideSsid>false</HideSsid>\n" +
                "                                <MaxClientCnt>0</MaxClientCnt>\n" +
                "                                <UserIsolation>false</UserIsolation>\n" +
                "                                <Description>aaaaaa</Description>\n" +
                "                            </Template>\n" +
                "                            <Template>\n" +
                "                                <Name>testst</Name>\n" +
                "                                <Enable>true</Enable>\n" +
                "                                <SSID>test</SSID>\n" +
                "                                <DefaultVlan>20</DefaultVlan>\n" +
                "                                <HideSsid>false</HideSsid>\n" +
                "                                <MaxClientCnt>0</MaxClientCnt>\n" +
                "                                <UserIsolation>false</UserIsolation>\n" +
                "                            </Template>\n" +
                "                            <Template>\n" +
                "                                <Name>service</Name>\n" +
                "                                <Enable>true</Enable>\n" +
                "                                <SSID>123456123456</SSID>\n" +
                "                                <DefaultVlan>1</DefaultVlan>\n" +
                "                                <HideSsid>false</HideSsid>\n" +
                "                                <MaxClientCnt>0</MaxClientCnt>\n" +
                "                                <UserIsolation>true</UserIsolation>\n" +
                "                            </Template>\n" +
                "                            <Template>\n" +
                "                                <Name>xkytest</Name>\n" +
                "                                <Enable>true</Enable>\n" +
                "                                <SSID>xkytest</SSID>\n" +
                "                                <DefaultVlan>20</DefaultVlan>\n" +
                "                                <HideSsid>false</HideSsid>\n" +
                "                                <MaxClientCnt>0</MaxClientCnt>\n" +
                "                                <UserIsolation>false</UserIsolation>\n" +
                "                                <Description>aaaaaaa</Description>\n" +
                "                            </Template>\n" +
                "                            <Template>\n" +
                "                                <Name>service1</Name>\n" +
                "                                <Enable>true</Enable>\n" +
                "                                <SSID>abc</SSID>\n" +
                "                                <DefaultVlan>2</DefaultVlan>\n" +
                "                                <HideSsid>false</HideSsid>\n" +
                "                                <MaxClientCnt>0</MaxClientCnt>\n" +
                "                                <UserIsolation>true</UserIsolation>\n" +
                "                            </Template>\n" +
                "                            <Template>\n" +
                "                                <Name>service3</Name>\n" +
                "                                <Enable>false</Enable>\n" +
                "                                <DefaultVlan>1</DefaultVlan>\n" +
                "                                <HideSsid>false</HideSsid>\n" +
                "                                <MaxClientCnt>0</MaxClientCnt>\n" +
                "                                <UserIsolation>false</UserIsolation>\n" +
                "                            </Template>\n" +
                "                            <Template>\n" +
                "                                <Name>fanbowen-test</Name>\n" +
                "                                <Enable>true</Enable>\n" +
                "                                <SSID>fanbowen-test</SSID>\n" +
                "                                <DefaultVlan>1</DefaultVlan>\n" +
                "                                <HideSsid>false</HideSsid>\n" +
                "                                <MaxClientCnt>0</MaxClientCnt>\n" +
                "                                <UserIsolation>false</UserIsolation>\n" +
                "                                <Description>3</Description>\n" +
                "                            </Template>\n" +
                "                        </ServiceTemplates>\n" +
                "                    </WLANClient>\n" +
                "                    <UserAccounts>\n" +
                "                        <UserGroups>\n" +
                "                            <Group>\n" +
                "                                <Name>system</Name>\n" +
                "                                <AuthorizationInfo>\n" +
                "                                    <FTPHomeDir>flash:</FTPHomeDir>\n" +
                "                                </AuthorizationInfo>\n" +
                "                            </Group>\n" +
                "                        </UserGroups>\n" +
                "                    </UserAccounts>\n" +
                "                    <AVC>\n" +
                "                        <TrafficPolicyProfiles>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>1</ProfileNumber>\n" +
                "                                <ProfileName>rule8bil</ProfileName>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>6</ProfileNumber>\n" +
                "                                <ProfileName>rule9bil</ProfileName>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>8</ProfileNumber>\n" +
                "                                <ProfileName>firstProfile</ProfileName>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>9</ProfileNumber>\n" +
                "                                <ProfileName>profi</ProfileName>\n" +
                "                                <DnMaxKbps>100000000</DnMaxKbps>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>10</ProfileNumber>\n" +
                "                                <ProfileName>rule6pptv</ProfileName>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>11</ProfileNumber>\n" +
                "                                <ProfileName>rule7pptv</ProfileName>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>12</ProfileNumber>\n" +
                "                                <ProfileName>txsp</ProfileName>\n" +
                "                                <DnMaxKbps>1024</DnMaxKbps>\n" +
                "                                <UpMaxKbps>30720</UpMaxKbps>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>14</ProfileNumber>\n" +
                "                                <ProfileName>qwe</ProfileName>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>15</ProfileNumber>\n" +
                "                                <ProfileName>123</ProfileName>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>16</ProfileNumber>\n" +
                "                                <ProfileName>111</ProfileName>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>17</ProfileNumber>\n" +
                "                                <ProfileName>https</ProfileName>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>18</ProfileNumber>\n" +
                "                                <ProfileName>ssidprofile</ProfileName>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>20</ProfileNumber>\n" +
                "                                <ProfileName>up</ProfileName>\n" +
                "                                <UpMaxKbps>10</UpMaxKbps>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>22</ProfileNumber>\n" +
                "                                <ProfileName>test</ProfileName>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>23</ProfileNumber>\n" +
                "                                <ProfileName>down1</ProfileName>\n" +
                "                                <DnMaxKbps>100</DnMaxKbps>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>24</ProfileNumber>\n" +
                "                                <ProfileName>svclimit</ProfileName>\n" +
                "                                <DnMaxKbps>1024</DnMaxKbps>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>25</ProfileNumber>\n" +
                "                                <ProfileName>ssidlimit</ProfileName>\n" +
                "                                <DnMaxKbps>100</DnMaxKbps>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>26</ProfileNumber>\n" +
                "                                <ProfileName>traffic_policy124_Rate</ProfileName>\n" +
                "                                <DnMaxKbps>10000</DnMaxKbps>\n" +
                "                                <UpMaxKbps>10000</UpMaxKbps>\n" +
                "                                <DnMaxKbpsPerIP>10000</DnMaxKbpsPerIP>\n" +
                "                                <UpMaxKbpsPerIP>10000</UpMaxKbpsPerIP>\n" +
                "                            </Profile>\n" +
                "                            <Profile>\n" +
                "                                <ProfileNumber>27</ProfileNumber>\n" +
                "                                <ProfileName>traffic_policy125_Rate</ProfileName>\n" +
                "                                <DnMaxKbps>10000</DnMaxKbps>\n" +
                "                                <UpMaxKbps>10000</UpMaxKbps>\n" +
                "                                <DnMaxKbpsPerIP>10000</DnMaxKbpsPerIP>\n" +
                "                                <UpMaxKbpsPerIP>10000</UpMaxKbpsPerIP>\n" +
                "                            </Profile>\n" +
                "                        </TrafficPolicyProfiles>\n" +
                "                        <TrafficPolicyRules>\n" +
                "                            <Rule>\n" +
                "                                <RuleNumber>123</RuleNumber>\n" +
                "                                <RuleName>ssidlimit</RuleName>\n" +
                "                                <Enable>true</Enable>\n" +
                "                            </Rule>\n" +
                "                            <Rule>\n" +
                "                                <RuleNumber>124</RuleNumber>\n" +
                "                                <RuleName>1111111</RuleName>\n" +
                "                                <Enable>true</Enable>\n" +
                "                                <TimeRange>123456</TimeRange>\n" +
                "                                <Action>\n" +
                "                                    <ProfileName>traffic_policy124_Rate</ProfileName>\n" +
                "                                </Action>\n" +
                "                            </Rule>\n" +
                "                            <Rule>\n" +
                "                                <RuleNumber>125</RuleNumber>\n" +
                "                                <RuleName>111111</RuleName>\n" +
                "                                <Enable>true</Enable>\n" +
                "                                <TimeRange>123456</TimeRange>\n" +
                "                                <Action>\n" +
                "                                    <ProfileName>traffic_policy125_Rate</ProfileName>\n" +
                "                                </Action>\n" +
                "                            </Rule>\n" +
                "                        </TrafficPolicyRules>\n" +
                "                        <RuleOptions>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>123</RuleNumber>\n" +
                "                                <OptionType>12</OptionType>\n" +
                "                                <OptionVal>abcd</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>124</RuleNumber>\n" +
                "                                <OptionType>8</OptionType>\n" +
                "                                <OptionVal>P2P</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>124</RuleNumber>\n" +
                "                                <OptionType>8</OptionType>\n" +
                "                                <OptionVal>地图导航</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>124</RuleNumber>\n" +
                "                                <OptionType>8</OptionType>\n" +
                "                                <OptionVal>流媒体</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>124</RuleNumber>\n" +
                "                                <OptionType>8</OptionType>\n" +
                "                                <OptionVal>生活服务</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>124</RuleNumber>\n" +
                "                                <OptionType>8</OptionType>\n" +
                "                                <OptionVal>网络社区</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>124</RuleNumber>\n" +
                "                                <OptionType>8</OptionType>\n" +
                "                                <OptionVal>系统工具</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>124</RuleNumber>\n" +
                "                                <OptionType>12</OptionType>\n" +
                "                                <OptionVal>lzxm</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>125</RuleNumber>\n" +
                "                                <OptionType>8</OptionType>\n" +
                "                                <OptionVal>P2P</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>125</RuleNumber>\n" +
                "                                <OptionType>8</OptionType>\n" +
                "                                <OptionVal>流媒体</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>125</RuleNumber>\n" +
                "                                <OptionType>8</OptionType>\n" +
                "                                <OptionVal>网络社区</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>125</RuleNumber>\n" +
                "                                <OptionType>8</OptionType>\n" +
                "                                <OptionVal>系统工具</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>125</RuleNumber>\n" +
                "                                <OptionType>8</OptionType>\n" +
                "                                <OptionVal>新闻资讯</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>125</RuleNumber>\n" +
                "                                <OptionType>8</OptionType>\n" +
                "                                <OptionVal>学习阅读</OptionVal>\n" +
                "                            </Option>\n" +
                "                            <Option>\n" +
                "                                <RuleNumber>125</RuleNumber>\n" +
                "                                <OptionType>12</OptionType>\n" +
                "                                <OptionVal>lzxm</OptionVal>\n" +
                "                            </Option>\n" +
                "                        </RuleOptions>\n" +
                "                    </AVC>\n" +
                "                    <APR>\n" +
                "                        <AppSubCategorys>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>1</ID>\n" +
                "                                <Name>即时通信</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>13</ID>\n" +
                "                                <Name>P2P</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>17</ID>\n" +
                "                                <Name>流媒体</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>46</ID>\n" +
                "                                <Name>E-Mail</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>51</ID>\n" +
                "                                <Name>网络社区</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>62</ID>\n" +
                "                                <Name>系统工具</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>63</ID>\n" +
                "                                <Name>地图导航</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>67</ID>\n" +
                "                                <Name>生活服务</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>82</ID>\n" +
                "                                <Name>学习阅读</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>95</ID>\n" +
                "                                <Name>新闻资讯</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>98</ID>\n" +
                "                                <Name>网络存储</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>99</ID>\n" +
                "                                <Name>搜索引擎</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>101</ID>\n" +
                "                                <Name>金融理财</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>108</ID>\n" +
                "                                <Name>游戏</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>120</ID>\n" +
                "                                <Name>网络下载</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>126</ID>\n" +
                "                                <Name>办公</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>127</ID>\n" +
                "                                <Name>网络协议</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                            <AppSubCategoryEntry>\n" +
                "                                <ID>142</ID>\n" +
                "                                <Name>其他业务</Name>\n" +
                "                            </AppSubCategoryEntry>\n" +
                "                        </AppSubCategorys>\n" +
                "                    </APR>\n" +
                "                    <TimeRange>\n" +
                "                        <PerRanges>\n" +
                "                            <PerRange>\n" +
                "                                <TimeRangeName>hellokitty123</TimeRangeName>\n" +
                "                                <ID>1</ID>\n" +
                "                                <StartTime>11:15</StartTime>\n" +
                "                                <EndTime>12:15</EndTime>\n" +
                "                                <DayOfWeek>\n" +
                "                                    <Sun>false</Sun>\n" +
                "                                    <Mon>false</Mon>\n" +
                "                                    <Tue>false</Tue>\n" +
                "                                    <Wed>false</Wed>\n" +
                "                                    <Thu>true</Thu>\n" +
                "                                    <Fri>true</Fri>\n" +
                "                                    <Sat>false</Sat>\n" +
                "                                </DayOfWeek>\n" +
                "                            </PerRange>\n" +
                "                            <PerRange>\n" +
                "                                <TimeRangeName>henfan</TimeRangeName>\n" +
                "                                <ID>1</ID>\n" +
                "                                <StartTime>01:00</StartTime>\n" +
                "                                <EndTime>02:00</EndTime>\n" +
                "                                <DayOfWeek>\n" +
                "                                    <Sun>false</Sun>\n" +
                "                                    <Mon>true</Mon>\n" +
                "                                    <Tue>false</Tue>\n" +
                "                                    <Wed>false</Wed>\n" +
                "                                    <Thu>false</Thu>\n" +
                "                                    <Fri>false</Fri>\n" +
                "                                    <Sat>false</Sat>\n" +
                "                                </DayOfWeek>\n" +
                "                            </PerRange>\n" +
                "                            <PerRange>\n" +
                "                                <TimeRangeName>henfan</TimeRangeName>\n" +
                "                                <ID>2</ID>\n" +
                "                                <StartTime>01:00</StartTime>\n" +
                "                                <EndTime>02:00</EndTime>\n" +
                "                                <DayOfWeek>\n" +
                "                                    <Sun>false</Sun>\n" +
                "                                    <Mon>false</Mon>\n" +
                "                                    <Tue>true</Tue>\n" +
                "                                    <Wed>false</Wed>\n" +
                "                                    <Thu>false</Thu>\n" +
                "                                    <Fri>false</Fri>\n" +
                "                                    <Sat>false</Sat>\n" +
                "                                </DayOfWeek>\n" +
                "                            </PerRange>\n" +
                "                            <PerRange>\n" +
                "                                <TimeRangeName>henfan</TimeRangeName>\n" +
                "                                <ID>3</ID>\n" +
                "                                <StartTime>01:00</StartTime>\n" +
                "                                <EndTime>02:00</EndTime>\n" +
                "                                <DayOfWeek>\n" +
                "                                    <Sun>false</Sun>\n" +
                "                                    <Mon>false</Mon>\n" +
                "                                    <Tue>false</Tue>\n" +
                "                                    <Wed>true</Wed>\n" +
                "                                    <Thu>false</Thu>\n" +
                "                                    <Fri>false</Fri>\n" +
                "                                    <Sat>false</Sat>\n" +
                "                                </DayOfWeek>\n" +
                "                            </PerRange>\n" +
                "                            <PerRange>\n" +
                "                                <TimeRangeName>henfan</TimeRangeName>\n" +
                "                                <ID>4</ID>\n" +
                "                                <StartTime>01:00</StartTime>\n" +
                "                                <EndTime>02:00</EndTime>\n" +
                "                                <DayOfWeek>\n" +
                "                                    <Sun>false</Sun>\n" +
                "                                    <Mon>false</Mon>\n" +
                "                                    <Tue>false</Tue>\n" +
                "                                    <Wed>false</Wed>\n" +
                "                                    <Thu>true</Thu>\n" +
                "                                    <Fri>false</Fri>\n" +
                "                                    <Sat>false</Sat>\n" +
                "                                </DayOfWeek>\n" +
                "                            </PerRange>\n" +
                "                            <PerRange>\n" +
                "                                <TimeRangeName>henfan</TimeRangeName>\n" +
                "                                <ID>5</ID>\n" +
                "                                <StartTime>01:00</StartTime>\n" +
                "                                <EndTime>02:00</EndTime>\n" +
                "                                <DayOfWeek>\n" +
                "                                    <Sun>false</Sun>\n" +
                "                                    <Mon>false</Mon>\n" +
                "                                    <Tue>false</Tue>\n" +
                "                                    <Wed>false</Wed>\n" +
                "                                    <Thu>false</Thu>\n" +
                "                                    <Fri>true</Fri>\n" +
                "                                    <Sat>false</Sat>\n" +
                "                                </DayOfWeek>\n" +
                "                            </PerRange>\n" +
                "                            <PerRange>\n" +
                "                                <TimeRangeName>henfan</TimeRangeName>\n" +
                "                                <ID>6</ID>\n" +
                "                                <StartTime>01:00</StartTime>\n" +
                "                                <EndTime>02:00</EndTime>\n" +
                "                                <DayOfWeek>\n" +
                "                                    <Sun>false</Sun>\n" +
                "                                    <Mon>false</Mon>\n" +
                "                                    <Tue>false</Tue>\n" +
                "                                    <Wed>false</Wed>\n" +
                "                                    <Thu>false</Thu>\n" +
                "                                    <Fri>false</Fri>\n" +
                "                                    <Sat>true</Sat>\n" +
                "                                </DayOfWeek>\n" +
                "                            </PerRange>\n" +
                "                            <PerRange>\n" +
                "                                <TimeRangeName>henfan</TimeRangeName>\n" +
                "                                <ID>7</ID>\n" +
                "                                <StartTime>01:00</StartTime>\n" +
                "                                <EndTime>02:00</EndTime>\n" +
                "                                <DayOfWeek>\n" +
                "                                    <Sun>true</Sun>\n" +
                "                                    <Mon>false</Mon>\n" +
                "                                    <Tue>false</Tue>\n" +
                "                                    <Wed>false</Wed>\n" +
                "                                    <Thu>false</Thu>\n" +
                "                                    <Fri>false</Fri>\n" +
                "                                    <Sat>false</Sat>\n" +
                "                                </DayOfWeek>\n" +
                "                            </PerRange>\n" +
                "                            <PerRange>\n" +
                "                                <TimeRangeName></TimeRangeName>\n" +
                "                                <ID>1</ID>\n" +
                "                                <StartTime>08:00</StartTime>\n" +
                "                                <EndTime>11:00</EndTime>\n" +
                "                                <DayOfWeek>\n" +
                "                                    <Sun>true</Sun>\n" +
                "                                    <Mon>false</Mon>\n" +
                "                                    <Tue>false</Tue>\n" +
                "                                    <Wed>false</Wed>\n" +
                "                                    <Thu>false</Thu>\n" +
                "                                    <Fri>false</Fri>\n" +
                "                                    <Sat>false</Sat>\n" +
                "                                </DayOfWeek>\n" +
                "                            </PerRange>\n" +
                "                        </PerRanges>\n" +
                "                    </TimeRange>\n" +
                "                    <OMS>\n" +
                "                        <IPv4Groups>\n" +
                "                            <Group>\n" +
                "                                <Name>2.2.2.2</Name>\n" +
                "                                <Description/>\n" +
                "                                <ObjNum>0</ObjNum>\n" +
                "                                <InUse>false</InUse>\n" +
                "                                <SecurityZone/>\n" +
                "                            </Group>\n" +
                "                            <Group>\n" +
                "                                <Name>desbaidu</Name>\n" +
                "                                <Description/>\n" +
                "                                <ObjNum>1</ObjNum>\n" +
                "                                <InUse>false</InUse>\n" +
                "                                <SecurityZone/>\n" +
                "                            </Group>\n" +
                "                            <Group>\n" +
                "                                <Name>exclude</Name>\n" +
                "                                <Description/>\n" +
                "                                <ObjNum>0</ObjNum>\n" +
                "                                <InUse>true</InUse>\n" +
                "                                <SecurityZone/>\n" +
                "                            </Group>\n" +
                "                            <Group>\n" +
                "                                <Name>hellokitty</Name>\n" +
                "                                <Description/>\n" +
                "                                <ObjNum>2</ObjNum>\n" +
                "                                <InUse>false</InUse>\n" +
                "                                <SecurityZone/>\n" +
                "                            </Group>\n" +
                "                            <Group>\n" +
                "                                <Name>iptest</Name>\n" +
                "                                <Description>ip 对象组创建</Description>\n" +
                "                                <ObjNum>1</ObjNum>\n" +
                "                                <InUse>false</InUse>\n" +
                "                                <SecurityZone/>\n" +
                "                            </Group>\n" +
                "                            <Group>\n" +
                "                                <Name>name</Name>\n" +
                "                                <Description/>\n" +
                "                                <ObjNum>0</ObjNum>\n" +
                "                                <InUse>false</InUse>\n" +
                "                                <SecurityZone/>\n" +
                "                            </Group>\n" +
                "                            <Group>\n" +
                "                                <Name>nihao</Name>\n" +
                "                                <Description/>\n" +
                "                                <ObjNum>1</ObjNum>\n" +
                "                                <InUse>true</InUse>\n" +
                "                                <SecurityZone/>\n" +
                "                            </Group>\n" +
                "                            <Group>\n" +
                "                                <Name>source</Name>\n" +
                "                                <Description/>\n" +
                "                                <ObjNum>1</ObjNum>\n" +
                "                                <InUse>false</InUse>\n" +
                "                                <SecurityZone/>\n" +
                "                            </Group>\n" +
                "                            <Group>\n" +
                "                                <Name>source2.0.0.6</Name>\n" +
                "                                <Description/>\n" +
                "                                <ObjNum>1</ObjNum>\n" +
                "                                <InUse>false</InUse>\n" +
                "                                <SecurityZone/>\n" +
                "                            </Group>\n" +
                "                            <Group>\n" +
                "                                <Name>sourcetest</Name>\n" +
                "                                <Description/>\n" +
                "                                <ObjNum>1</ObjNum>\n" +
                "                                <InUse>false</InUse>\n" +
                "                                <SecurityZone/>\n" +
                "                            </Group>\n" +
                "                            <Group>\n" +
                "                                <Name>urlfilter</Name>\n" +
                "                                <Description/>\n" +
                "                                <ObjNum>1</ObjNum>\n" +
                "                                <InUse>false</InUse>\n" +
                "                                <SecurityZone/>\n" +
                "                            </Group>\n" +
                "                            <Group>\n" +
                "                                <Name>xinhua</Name>\n" +
                "                                <Description/>\n" +
                "                                <ObjNum>1</ObjNum>\n" +
                "                                <InUse>false</InUse>\n" +
                "                                <SecurityZone/>\n" +
                "                            </Group>\n" +
                "                        </IPv4Groups>\n" +
                "                        <IPv4Objs>\n" +
                "                            <Obj>\n" +
                "                                <Group>desbaidu</Group>\n" +
                "                                <ID>0</ID>\n" +
                "                                <Type>4</Type>\n" +
                "                                <HostName>www.baidu.com</HostName>\n" +
                "                            </Obj>\n" +
                "                            <Obj>\n" +
                "                                <Group>hellokitty</Group>\n" +
                "                                <ID>0</ID>\n" +
                "                                <Type>1</Type>\n" +
                "                                <SubnetIPv4Address>192.168.0.0</SubnetIPv4Address>\n" +
                "                                <IPv4Mask>255.255.0.0</IPv4Mask>\n" +
                "                            </Obj>\n" +
                "                            <Obj>\n" +
                "                                <Group>hellokitty</Group>\n" +
                "                                <ID>10</ID>\n" +
                "                                <Type>1</Type>\n" +
                "                                <SubnetIPv4Address>192.167.0.0</SubnetIPv4Address>\n" +
                "                                <IPv4Mask>255.255.0.0</IPv4Mask>\n" +
                "                            </Obj>\n" +
                "                            <Obj>\n" +
                "                                <Group>iptest</Group>\n" +
                "                                <ID>0</ID>\n" +
                "                                <Type>3</Type>\n" +
                "                                <HostIPv4Address>180.101.49.12</HostIPv4Address>\n" +
                "                            </Obj>\n" +
                "                            <Obj>\n" +
                "                                <Group>nihao</Group>\n" +
                "                                <ID>0</ID>\n" +
                "                                <Type>3</Type>\n" +
                "                                <HostIPv4Address>192.168.0.100</HostIPv4Address>\n" +
                "                            </Obj>\n" +
                "                            <Obj>\n" +
                "                                <Group>source</Group>\n" +
                "                                <ID>0</ID>\n" +
                "                                <Type>1</Type>\n" +
                "                                <SubnetIPv4Address>192.168.1.0</SubnetIPv4Address>\n" +
                "                                <IPv4Mask>255.255.255.0</IPv4Mask>\n" +
                "                            </Obj>\n" +
                "                            <Obj>\n" +
                "                                <Group>source2.0.0.6</Group>\n" +
                "                                <ID>0</ID>\n" +
                "                                <Type>3</Type>\n" +
                "                                <HostIPv4Address>2.2.2.6</HostIPv4Address>\n" +
                "                            </Obj>\n" +
                "                            <Obj>\n" +
                "                                <Group>sourcetest</Group>\n" +
                "                                <ID>0</ID>\n" +
                "                                <Type>3</Type>\n" +
                "                                <HostIPv4Address>2.2.2.2</HostIPv4Address>\n" +
                "                            </Obj>\n" +
                "                            <Obj>\n" +
                "                                <Group>urlfilter</Group>\n" +
                "                                <ID>0</ID>\n" +
                "                                <Type>1</Type>\n" +
                "                                <SubnetIPv4Address>2.2.2.0</SubnetIPv4Address>\n" +
                "                                <IPv4Mask>255.255.255.0</IPv4Mask>\n" +
                "                            </Obj>\n" +
                "                            <Obj>\n" +
                "                                <Group>xinhua</Group>\n" +
                "                                <ID>0</ID>\n" +
                "                                <Type>4</Type>\n" +
                "                                <HostName>m.xinhuanet.com</HostName>\n" +
                "                            </Obj>\n" +
                "                        </IPv4Objs>\n" +
                "                    </OMS>\n" +
                "                    <AP>\n" +
                "                        <AllAP>\n" +
                "                            <AP>\n" +
                "                                <Name>ap1</Name>\n" +
                "                                <LocationName>default-location</LocationName>\n" +
                "                                <Status>1</Status>\n" +
                "                                <Type>2</Type>\n" +
                "                                <GroupName>default-group</GroupName>\n" +
                "                            </AP>\n" +
                "                        </AllAP>\n" +
                "                        <APGroup>\n" +
                "                            <Group>\n" +
                "                                <Name>default-group</Name>\n" +
                "                                <RuleNum>0</RuleNum>\n" +
                "                                <ModelNum>0</ModelNum>\n" +
                "                                <APNum>1</APNum>\n" +
                "                                <RegionCode>156</RegionCode>\n" +
                "                                <LocationName>default-location</LocationName>\n" +
                "                                <Description/>\n" +
                "                            </Group>\n" +
                "                            <Group>\n" +
                "                                <Name>1</Name>\n" +
                "                                <RuleNum>0</RuleNum>\n" +
                "                                <ModelNum>0</ModelNum>\n" +
                "                                <APNum>0</APNum>\n" +
                "                                <RegionCode>156</RegionCode>\n" +
                "                                <LocationName>default-location</LocationName>\n" +
                "                                <Description/>\n" +
                "                            </Group>\n" +
                "                        </APGroup>\n" +
                "                    </AP>\n" +
                "                </top>\n" +
                "            </data>\n" +
                "        </rpc-reply>\n" +
                "    </env:Body>\n" +
                "</env:Envelope>";

        long start1 = System.currentTimeMillis();
        MessageDigest sha1 = MessageDigest.getInstance("SHA1");
        sha1.update(buffer.getBytes());
        byte[] digest1 = sha1.digest();
        BigInteger bigInt1 = new BigInteger(digest1);
        long end1 = System.currentTimeMillis();
        System.out.println(bigInt1.toString());
        System.out.println(bigInt1.bitLength());
        System.out.println("use time : "+ (end1 - start1) + "ms");

        long start = System.currentTimeMillis();
        MessageDigest md5 = MessageDigest.getInstance("MD5");
        md5.update(buffer.getBytes());
        byte[] digest = md5.digest();
        BigInteger bigInt = new BigInteger(digest);
        long end = System.currentTimeMillis();
        System.out.println(bigInt.toString());
        System.out.println(bigInt.bitLength());
        System.out.println("use time : "+ (end - start) + "ms");

        start = System.currentTimeMillis();
        int hashCode = buffer.hashCode();
        end = System.currentTimeMillis();
        System.out.println("hashCode : " + hashCode);
        System.out.println("use time : " + (end - start) + "ms");


    }
}
