package com.dotwait.md5;

import org.junit.Test;

public class Sha1Test {
    @Test
    public void sha1Test() {
        String buffer =

                "                                <CategoryName>摩托车和自行车</CategoryName>\n" +
                "                                <Critical>390</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供摩托车、自行车介绍、测评和展览等相关信息的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>99</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>搬家</CategoryName>\n" +
                "                                <Critical>240</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供搬家服务的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>136</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>音乐</CategoryName>\n" +
                "                                <Critical>215</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供音乐和乐器相关信息介绍的网站。不包括歌曲下载和在线音乐类网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>126</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>导航网站</CategoryName>\n" +
                "                                <Critical>345</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供网站导航服务的网站，如hao123等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>67</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>网络借贷</CategoryName>\n" +
                "                                <Critical>1000</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供网络借贷等相关内容的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>187</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>网络和通信</CategoryName>\n" +
                "                                <Critical>10</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供网络产品、手机、通信设备介绍的网站，以及开发这些产品的厂商官网等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>105</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>新闻</CategoryName>\n" +
                "                                <Critical>300</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>报道新闻和实事的网站，例如新闻报纸、新闻服务、个人新闻服务、广播站点和杂志。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>6</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>裸体和人体艺术</CategoryName>\n" +
                "                                <Critical>950</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>含有人体艺术、裸体相关内容的网站，其内容并无明显与性相关。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>45</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>在线广播</CategoryName>\n" +
                "                                <Critical>200</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供在线听广播服务的各种网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>92</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>在线聊天</CategoryName>\n" +
                "                                <Critical>545</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>通过在线方式进行聊天的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>116</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>在线音乐</CategoryName>\n" +
                "                                <Critical>205</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供在线听音乐服务的各种网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>93</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>在线支付</CategoryName>\n" +
                "                                <Critical>285</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供在线支付、收款业务的网站或者与之相关的公司网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>88</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>在线购物</CategoryName>\n" +
                "                                <Critical>70</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供各种方式在线购物的网站，如购物平台、二手交易、物品置换等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>95</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>网络存储</CategoryName>\n" +
                "                                <Critical>540</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供网络存储服务的网站，如各种网盘等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>160</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>在线视频</CategoryName>\n" +
                "                                <Critical>195</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供在线观看视频、电影、电视剧、纪录片等服务的各种网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>91</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>普通娱乐场所</CategoryName>\n" +
                "                                <Critical>310</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供动物园、公共娱乐中心、水池、娱乐公园等场所信息的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>120</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>其他类</CategoryName>\n" +
                "                                <Critical>120</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>其他类</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>186</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>其他成人类网站</CategoryName>\n" +
                "                                <Critical>920</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>未分类到成人二级分类的其他成人相关的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>173</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>其他下载</CategoryName>\n" +
                "                                <Critical>190</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>未分类到下载二级分类的其他下载相关的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>73</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>其他时尚</CategoryName>\n" +
                "                                <Critical>165</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>未分类到时尚二级分类的其他时尚相关的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>132</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>其他金融</CategoryName>\n" +
                "                                <Critical>295</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>未分类到理财二级分类的其他理财相关的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>90</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>其他生活</CategoryName>\n" +
                "                                <Critical>270</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>综合性的或其他类型的参考信息，如交通违章、空气质量、云笔记、百科、在线翻译、字典等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>142</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>P2P应用软件</CategoryName>\n" +
                "                                <Critical>585</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>P2P下载软件和应用介绍或者厂商的网站，如迅雷等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>68</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>待启用网站</CategoryName>\n" +
                "                                <Critical>110</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>不活跃的，为后续使用保留的网站。此类网站通常不包含他们自己的内容，可能仅仅显示“正在建设中”，“购买这个域名”，或显示广告。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>184</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>个人站点</CategoryName>\n" +
                "                                <Critical>45</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>个人相关或由个人主持的网站，包括那些在挂载在商业网站上的站点。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>9</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>宠物和动物</CategoryName>\n" +
                "                                <Critical>250</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供宠物和动物的介绍，饲养，研究以及交流等相关系信息的网站</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>138</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>钓鱼网站</CategoryName>\n" +
                "                                <Critical>900</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>仿冒的用于钓鱼攻击的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>176</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>图片下载</CategoryName>\n" +
                "                                <Critical>185</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供图片资源、桌面主题、桌面墙纸、素材等下载的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>72</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>图片分享</CategoryName>\n" +
                "                                <Critical>530</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>包含数字相片和图像并允许交换在线相册和数字图像的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>121</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>政治宣传</CategoryName>\n" +
                "                                <Critical>495</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>由政治团体资助，宣扬不同的政治观点的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>40</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>色情网站</CategoryName>\n" +
                "                                <Critical>985</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供色情服务，色情资源的网站，如色情交易、色情电影、色情图片、色情小说等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>167</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>学前教育</CategoryName>\n" +
                "                                <Critical>90</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>与学前教育相关的网站，如相关主页，以及相关的特长信息等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>82</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>育儿</CategoryName>\n" +
                "                                <Critical>230</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>包括怀孕知识、育儿知识、胎教等相关的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>134</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>中小学教育</CategoryName>\n" +
                "                                <Critical>85</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>与中学和小学教育相关的网站，如学校主页，以及相关的辅导信息等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>81</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>房产开发</CategoryName>\n" +
                "                                <Critical>425</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>各房地产开发公司官网。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>75</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>房产交易</CategoryName>\n" +
                "                                <Critical>430</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供商业或住宅房地产相关服务的网站，包括介绍、租赁、购买、出售或融资购买住宅、办公室等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>76</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>宗教</CategoryName>\n" +
                "                                <Critical>505</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>与信念、人类精神或宗教信仰相关的网站。包括教派、教堂、清真寺和其它礼拜堂网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>44</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>校园欺诈</CategoryName>\n" +
                "                                <Critical>570</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>助长不道德行为的网站，例如通过提供测试答案、书写随笔、研究论文或学期报告进行作弊或剽窃。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>60</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>科研</CategoryName>\n" +
                "                                <Critical>105</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>由个科研机构创办的网站，以及各种与科学研究相关的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>85</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>搜索门户</CategoryName>\n" +
                "                                <Critical>340</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供网页、新闻组、图像、目录、和其它在线内容搜索能力的网站。包括门户和目录网址，例如白页和黄页。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>0</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>服务业</CategoryName>\n" +
                "                                <Critical>55</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>包括除工业、农业外的第三产业信息，如印刷、商务活动组织、展会策划、礼仪庆典、搬家公司等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>151</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>两性健康</CategoryName>\n" +
                "                                <Critical>995</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供与两性健康、性病、性爱技巧等相关内容的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>169</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>船</CategoryName>\n" +
                "                                <Critical>380</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>介绍、买卖、维修各类船只，船舶的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>97</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>购物指南</CategoryName>\n" +
                "                                <Critical>65</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供购物指导、价格比较等信息的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>94</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>社会问题</CategoryName>\n" +
                "                                <Critical>480</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>用于介绍或讨论社会问题的网站，如延迟退休、劳动保障、社会保障、养老等问题等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>165</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>软件下载</CategoryName>\n" +
                "                                <Critical>175</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供各种软件资源下载的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>70</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>技术及资讯</CategoryName>\n" +
                "                                <Critical>5</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>介绍各种软件技术，开发技术的网站，如编程技术、图像处理软件、辅助工具等，以及各种IT资讯类网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>104</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>升级服务</CategoryName>\n" +
                "                                <Critical>35</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供软件程序、应用和杀毒软件、安全类产品病毒特征库、攻击特征库升级服务的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>110</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>垃圾邮件</CategoryName>\n" +
                "                                <Critical>575</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供垃圾邮件服务，或者通过垃圾邮件技术推广的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>177</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>特殊领域组织</CategoryName>\n" +
                "                                <Critical>560</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>一些特定领域的爱好者或者相关组织创建的网站，用于宣传或交流该领域的一些知识信息，不包括政府相关的领域。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>161</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>特别行业</CategoryName>\n" +
                "                                <Critical>405</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>一些可能存在着争议的行业，可能处在法律允许的边缘，如民间借贷、代孕、讨债公司、私家侦探等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>154</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>体育</CategoryName>\n" +
                "                                <Critical>350</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>体育队、球迷俱乐部、比分和体育新闻相关的网站。包括所有运动，无论职业还是休闲。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>17</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>自杀</CategoryName>\n" +
                "                                <Critical>975</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>讨论或者介绍自杀方面内容的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>178</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>刺青和纹身</CategoryName>\n" +
                "                                <Critical>160</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供刺青或纹身等服务或介绍的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>131</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>少儿</CategoryName>\n" +
                "                                <Critical>260</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>以小朋友为主要目标群建设的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>140</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>票务</CategoryName>\n" +
                "                                <Critical>255</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供票务服务的网站，包括各种演出门票、电影票等。不包括火车票，飞机票等交通工具票务。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>139</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>票务和酒店</CategoryName>\n" +
                "                                <Critical>130</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>在线订购旅行服务（如机票、住宿预定、汽车租赁）的网站</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>102</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>烟草</CategoryName>\n" +
                "                                <Critical>955</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>生产和销售烟草相关产品的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>148</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>玩具</CategoryName>\n" +
                "                                <Critical>305</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>介绍或者展示各种玩具，模型的网站，不包括成人玩具。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>118</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>技能培训</CategoryName>\n" +
                "                                <Critical>95</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供各种职业技能培训和考试信息的站点，如驾驶培训、厨师培训、挖掘机培训、成人教育、远程教育、会计考试、司法考试等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>83</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>翻译绕过</CategoryName>\n" +
                "                                <Critical>555</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>将网页或其中语句从一种语言翻译成另一种语言的网站。这些网站可以用来试图绕过过滤系统。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>112</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>出行指南</CategoryName>\n" +
                "                                <Critical>135</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供各种辅助出行信息的网站，如天气预报、地图、路况、公交线路、列车时刻等。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>133</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>网络电话</CategoryName>\n" +
                "                                <Critical>20</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供在线拨打电话或者提供相关信息的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>107</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>交通工具租赁</CategoryName>\n" +
                "                                <Critical>395</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>与汽车租赁、巴士租赁、自行车、飞机和船等交通工具租赁相关的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>100</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>视频会议</CategoryName>\n" +
                "                                <Critical>25</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>提供在线视频会议的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>108</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>暴力</CategoryName>\n" +
                "                                <Critical>925</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>包含描绘或鼓吹攻击人类、动物或机构的图片或文字的网站。例如包含令人触目惊心的血迹，创伤，或虐待动物等可怕内容的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>54</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>低俗</CategoryName>\n" +
                "                                <Critical>910</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>页面主要为成人笑话、偷拍走光等的内容的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>171</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>武器</CategoryName>\n" +
                "                                <Critical>550</Critical>\n" +
                "                                <CategoryType>0</CategoryType>\n" +
                "                                <Description>描述、销售、评论枪支和武器（包括娱乐目的的武器）的网站。</Description>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>50</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>360</CategoryName>\n" +
                "                                <Critical>1500</Critical>\n" +
                "                                <CategoryType>1</CategoryType>\n" +
                "                                <Description/>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>255</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>h3c</CategoryName>\n" +
                "                                <Critical>2001</Critical>\n" +
                "                                <CategoryType>1</CategoryType>\n" +
                "                                <Description/>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>255</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>speedtest</CategoryName>\n" +
                "                                <Critical>2002</Critical>\n" +
                "                                <CategoryType>1</CategoryType>\n" +
                "                                <Description/>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>255</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                            <Category>\n" +
                "                                <CategoryName>youku</CategoryName>\n" +
                "                                <Critical>2000</Critical>\n" +
                "                                <CategoryType>1</CategoryType>\n" +
                "                                <Description/>\n" +
                "                                <PreCategoryReferred/>\n" +
                "                                <PreCategoryID>255</PreCategoryID>\n" +
                "                            </Category>\n" +
                "                        </Categories>\n" +
                "                        <RuleInCategory>\n" +
                "                            <Rule>\n" +
                "                                <CategoryName>360</CategoryName>\n" +
                "                                <RuleID>1</RuleID>\n" +
                "                                <HostType>1</HostType>\n" +
                "                                <HostName>www.speedtest.cn</HostName>\n" +
                "                                <URIType>0</URIType>\n" +
                "                                <URIString/>\n" +
                "                            </Rule>\n" +
                "                            <Rule>\n" +
                "                                <CategoryName>h3c</CategoryName>\n" +
                "                                <RuleID>1</RuleID>\n" +
                "                                <HostType>1</HostType>\n" +
                "                                <HostName>www.h3c.com</HostName>\n" +
                "                                <URIType>0</URIType>\n" +
                "                                <URIString/>\n" +
                "                            </Rule>\n" +
                "                            <Rule>\n" +
                "                                <CategoryName>speedtest</CategoryName>\n" +
                "                                <RuleID>1</RuleID>\n" +
                "                                <HostType>2</HostType>\n" +
                "                                <HostName>test</HostName>\n" +
                "                                <URIType>0</URIType>\n" +
                "                                <URIString/>\n" +
                "                            </Rule>\n" +
                "                            <Rule>\n" +
                "                                <CategoryName>speedtest</CategoryName>\n" +
                "                                <RuleID>2</RuleID>\n" +
                "                                <HostType>1</HostType>\n" +
                "                                <HostName>www.youku.com</HostName>\n" +
                "                                <URIType>0</URIType>\n" +
                "                                <URIString/>\n" +
                "                            </Rule>\n" +
                "                            <Rule>\n" +
                "                                <CategoryName>youku</CategoryName>\n" +
                "                                <RuleID>1</RuleID>\n" +
                "                                <HostType>1</HostType>\n" +
                "                                <HostName>www.youku.com</HostName>\n" +
                "                                <URIType>0</URIType>\n" +
                "                                <URIString/>\n" +
                "                            </Rule>\n" +
                "                        </RuleInCategory>\n" +
                "                        <ParentCategories>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>IT技术</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>9</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>26</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>104</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>105</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>106</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>107</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>108</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>109</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>110</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>111</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>112</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>P2P和影视下载</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>68</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>69</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>博彩和赌博</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>179</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>180</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>成人</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>45</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>168</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>169</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>170</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>171</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>172</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>173</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>待启用网站</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>184</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>电子邮箱</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>159</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>毒品</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>181</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>恶意网站</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>19</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>64</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>175</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>176</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>177</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>法律</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>158</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>房地产</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>75</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>76</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>77</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>78</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>购物</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>94</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>95</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>黑客</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>57</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>健康和医疗</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>143</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>144</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>145</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>146</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>交通工具</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>96</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>97</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>98</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>99</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>100</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>教育和科研</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>79</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>80</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>81</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>82</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>83</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>84</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>85</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>金融</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>86</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>87</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>88</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>89</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>90</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>187</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>军事和武器</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>50</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>156</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>流媒体和视频</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>91</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>92</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>93</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>旅行</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>101</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>102</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>论坛</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>103</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>普通下载</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>70</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>71</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>72</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>73</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>其他类</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>186</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>歧视,暴力和犯罪</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>54</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>56</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>182</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>183</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>求职招聘</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>74</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>人文</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>124</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>125</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>126</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>色情网站</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>167</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>商业</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>16</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>150</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>151</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>152</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>153</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>154</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>社会焦点</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>162</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>163</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>164</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>165</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>166</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>社交网络</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>46</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>121</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>122</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>123</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                            </ParentCategory>\n" +
                "                            <ParentCategory>\n" +
                "                                <ParentCategoryName>生活参考</ParentCategoryName>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>133</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>134</PreCategoryID>\n" +
                "                                </PreCategoryIDs>\n" +
                "                                <PreCategoryIDs>\n" +
                "                                    <PreCategoryID>135</PreCategoryID>\n";
        long start = System.currentTimeMillis();
        String encrypt = Sha1Util.encrypt(buffer.trim());
        long end = System.currentTimeMillis();
        System.out.println(encrypt);
        System.out.println("use time : " + (end - start) + "ms");
    }
}
